In [2]:
import tensorflow as tf
import keras
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt 

data = []
labels = []


shared_dir = '/Users/prateek/Desktop/ML/Major/augmented/'
infected_dir = shared_dir + 'True_parasitized/'
uninfected_dir = shared_dir + 'True_uninfected/'
input_shape = [32, 32]
batch = 32

def reading(path):
    mode = cv2.IMREAD_GRAYSCALE
    img_read = cv2.imread(path)#, mode)
    # img_read = cv2.cvtColor(img_read, cv2.COLOR_BGR2RGB)
    img_read = np.float32(img_read)
    img_read = cv2.cvtColor(img_read, cv2.COLOR_BGR2HSV_FULL)
    img_resize = cv2.resize(img_read, input_shape)
    return img_resize

parasitized_data = os.listdir(infected_dir)
uninfected_data = os.listdir(uninfected_dir)

for img in parasitized_data:
    try:
        data.append(reading(infected_dir + img))
        labels.append(1)
    except Exception as e:
        print(e)
    
for img in uninfected_data:
    try:
        data.append(reading(uninfected_dir + img))
        labels.append(0)
    except Exception as e:
        print(e)

shared_dir = '/Users/prateek/Desktop/ML/Major/augmented/'
infected_dir = shared_dir + 'False_uninfected/'
uninfected_dir = shared_dir + 'False_parasitized/'

parasitized_data = os.listdir(infected_dir)
uninfected_data = os.listdir(uninfected_dir)


for img in parasitized_data:
    try:
        data.append(reading(infected_dir + img))
        labels.append(1)
    except Exception as e:
        print(e)
    
for img in uninfected_data:
    try:
        data.append(reading(uninfected_dir + img))
        labels.append(0)
    except Exception as e:
        print(e)

image_data = np.array(data)
labels = np.array(labels)
# input_shape.append(3)

print("image_shape:", input_shape)
print("image_data:",len(image_data))
print("labels:",len(labels))

image_shape: [32, 32]
image_data: 275580
labels: 275580


In [3]:
bins = [i * 5 for i in range(0,36*2+1)]
print(bins)
histo = []
for image in image_data:
    hist, bin = np.histogram(image, bins=bins)
    histo.append(hist)
data = np.asarray(histo)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360]


In [4]:
from sklearn.model_selection import train_test_split
from keras.utils import np_utils

X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size = 0.1,random_state = 0)

y_train = np_utils.to_categorical(y_train, num_classes = 2)
y_test = np_utils.to_categorical(y_test, num_classes = 2)

print("X_train:",len(X_train))
print("X_test:",len(X_test))
print("y_train:",len(y_train))
print("y_test:",len(y_test))

X_train: 248022
X_test: 27558
y_train: 248022
y_test: 27558


In [5]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 10)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [6]:
y_pred = classifier.predict(X_test)

In [7]:
print(y_pred)
print(y_test)

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [8]:
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score

print(confusion_matrix( y_test.argmax(axis=1), y_pred.argmax(axis=1) ))
print(accuracy_score(y_test, y_pred))
print(precision_score( y_test, y_pred, average='micro') )
print(recall_score( y_test, y_pred, average='micro') )

[[11107  2633]
 [ 2522 11296]]
0.8129399811307062
0.8129399811307062
0.8129399811307062
